import { addDays, format, subDays } from "date-fns";
import { AS_OF } from "./as-of";
import type { GateEvent, Invoice } from "./types";

function day(offset: number) {
  return format(addDays(AS_OF, offset), "yyyy-MM-dd");
}

function ago(daysBack: number) {
  return format(subDays(AS_OF, daysBack), "yyyy-MM-dd");
}

function stamp(daysBack: number, hour: number, minute = 0) {
  const d = subDays(AS_OF, daysBack);
  return `${format(d, "yyyy-MM-dd")}T${String(hour).padStart(2, "0")}:${String(minute).padStart(2, "0")}:00`;
}

const BILLED = "Northbridge Logistics LLC";

function chargeSpan(endAgo: number, count: number) {
  const end = subDays(AS_OF, endAgo);
  const start = subDays(end, count - 1);
  return Array.from({ length: count }, (_, i) => format(addDays(start, i), "yyyy-MM-dd"));
}

export function makeSeed(): { invoices: Invoice[]; gates: GateEvent[] } {
  const invoices: Invoice[] = [
    {
      id: "inv_msc_8821",
      invoiceNumber: "MSC-DND-88214",
      chargeType: "demurrage",
      direction: "import",
      billingParty: "MSC Mediterranean Shipping",
      billingPartyType: "VOCC",
      billedParty: BILLED,
      bolNumber: "MEDUUN24031887",
      containerNumber: "MSCU2948176",
      port: "New York / New Jersey",
      terminal: "APM Terminals Elizabeth",
      liabilityBasis: "Consignee named on bill of lading MEDUUN24031887.",
      invoiceDate: ago(24),
      dueDate: day(6),
      freeTimeDays: 4,
      freeTimeStart: ago(38),
      freeTimeEnd: ago(34),
      availabilityDate: null,
      earliestReturnDate: null,
      chargeDates: chargeSpan(30, 4),
      amountDue: 12400,
      tariffRule: "MSC Rule Tariff 004 — Demurrage NY/NJ",
      dailyRate: 310,
      contactEmail: "dnd.us@msc.com",
      contactPhone: "+1 212 764 4800",
      disputeUrl: "https://www.msc.com/usa/help-centre/demurrage-detention",
      disputeWindowDays: 30,
      certFmcConsistent: false,
      certPerformanceClean: false,
      lastChargeDate: ago(30),
      holdReason: null,
      status: "open",
      disputeId: null,
    },
    {
      id: "inv_mae_6102",
      invoiceNumber: "MAEU-DT-610293",
      chargeType: "detention",
      direction: "import",
      billingParty: "Maersk A/S",
      billingPartyType: "VOCC",
      billedParty: BILLED,
      bolNumber: "MAEU588210441",
      containerNumber: "MAEU6102934",
      port: "New York / New Jersey",
      terminal: "Maher Terminals",
      liabilityBasis: "Merchant contracting for inland haulage under service contract SC-441-26.",
      invoiceDate: ago(27),
      dueDate: day(3),
      freeTimeDays: 5,
      freeTimeStart: ago(40),
      freeTimeEnd: null,
      availabilityDate: ago(40),
      earliestReturnDate: ago(35),
      chargeDates: chargeSpan(32, 6),
      amountDue: 8200,
      tariffRule: "Maersk Detention Tariff USWC/USEC 2.4",
      dailyRate: 275,
      contactEmail: "us.detention@maersk.com",
      contactPhone: "+1 973 514 5000",
      disputeUrl: "https://www.maersk.com/support/demurrage-detention",
      disputeWindowDays: 30,
      certFmcConsistent: true,
      certPerformanceClean: true,
      lastChargeDate: ago(32),
      holdReason: null,
      status: "open",
      disputeId: null,
    },
    {
      id: "inv_cma_8471",
      invoiceNumber: "CMA-DM-847120",
      chargeType: "demurrage",
      direction: "import",
      billingParty: "CMA CGM",
      billingPartyType: "VOCC",
      billedParty: BILLED,
      bolNumber: "CMDUUSNYC246611",
      containerNumber: "CMAU8471203",
      port: "Los Angeles",
      terminal: "WBCT",
      liabilityBasis: "Consignee on bill of lading.",
      invoiceDate: ago(18),
      dueDate: day(12),
      freeTimeDays: 4,
      freeTimeStart: ago(33),
      freeTimeEnd: ago(29),
      availabilityDate: ago(33),
      earliestReturnDate: null,
      chargeDates: chargeSpan(26, 3),
      amountDue: 6750,
      tariffRule: "CMA CGM Demurrage POLA Rule 23",
      dailyRate: 2250,
      contactEmail: "us.dnd@cma-cgm.com",
      contactPhone: "+1 757 961 2100",
      disputeUrl: "https://www.cma-cgm.com/ebusiness/detention-demurrage",
      disputeWindowDays: 30,
      certFmcConsistent: true,
      certPerformanceClean: true,
      lastChargeDate: ago(26),
      holdReason: null,
      status: "open",
      disputeId: null,
    },
    {
      id: "inv_cos_1190",
      invoiceNumber: "COSCO-DM-119044",
      chargeType: "demurrage",
      direction: "import",
      billingParty: "COSCO Shipping",
      billingPartyType: "VOCC",
      billedParty: BILLED,
      bolNumber: "COSU6369102280",
      containerNumber: "CSNU1190448",
      port: "Long Beach",
      terminal: "TTI Long Beach",
      liabilityBasis: "Named consignee; contracted for ocean carriage under SC COS-882.",
      invoiceDate: ago(8),
      dueDate: day(22),
      freeTimeDays: 4,
      freeTimeStart: ago(20),
      freeTimeEnd: ago(16),
      availabilityDate: ago(20),
      earliestReturnDate: null,
      chargeDates: chargeSpan(14, 2),
      amountDue: 3200,
      tariffRule: "COSCO America Demurrage POLB 1.2",
      dailyRate: 1600,
      contactEmail: "dnd.usa@coscon.com",
      contactPhone: "+1 866 830 2550",
      disputeUrl: "https://elines.coscoshipping.com/ebusiness/help/dnd",
      disputeWindowDays: 30,
      certFmcConsistent: true,
      certPerformanceClean: true,
      lastChargeDate: ago(14),
      holdReason: null,
      status: "open",
      disputeId: null,
    },
    {
      id: "inv_evr_3301",
      invoiceNumber: "EGLV-DM-330184",
      chargeType: "demurrage",
      direction: "import",
      billingParty: "Evergreen Line",
      billingPartyType: "VOCC",
      billedParty: BILLED,
      bolNumber: "EGLV0033601194",
      containerNumber: "EGHU3301842",
      port: "Oakland",
      terminal: "TraPac Oakland",
      liabilityBasis: "Merchant under NVOCC house bill, ocean carrier invoice passed through.",
      invoiceDate: ago(22),
      dueDate: day(8),
      freeTimeDays: 5,
      freeTimeStart: ago(36),
      freeTimeEnd: ago(31),
      availabilityDate: ago(36),
      earliestReturnDate: null,
      chargeDates: chargeSpan(28, 4),
      amountDue: 9100,
      tariffRule: "Evergreen Demurrage Oakland T-04",
      dailyRate: 2275,
      contactEmail: null,
      contactPhone: null,
      disputeUrl: null,
      disputeWindowDays: null,
      certFmcConsistent: true,
      certPerformanceClean: true,
      lastChargeDate: ago(28),
      holdReason: null,
      status: "open",
      disputeId: null,
    },
    {
      id: "inv_one_5520",
      invoiceNumber: "ONEY-DT-552018",
      chargeType: "detention",
      direction: "import",
      billingParty: "Ocean Network Express",
      billingPartyType: "VOCC",
      billedParty: BILLED,
      bolNumber: "ONEYNYC2491187",
      containerNumber: "TCLU5520189",
      port: "New York / New Jersey",
      terminal: "APM Terminals Elizabeth",
      liabilityBasis: "Contracting merchant for combined transport.",
      invoiceDate: ago(12),
      dueDate: day(18),
      freeTimeDays: 4,
      freeTimeStart: ago(58),
      freeTimeEnd: ago(54),
      availabilityDate: ago(58),
      earliestReturnDate: ago(54),
      chargeDates: chargeSpan(48, 8),
      amountDue: 15800,
      tariffRule: "ONE US Detention 3.1",
      dailyRate: 1975,
      contactEmail: "usa.dnd@one-line.com",
      contactPhone: "+1 201 678 4000",
      disputeUrl: "https://ecomm.one-line.com/one-ecom/dispute",
      disputeWindowDays: 30,
      certFmcConsistent: true,
      certPerformanceClean: true,
      lastChargeDate: ago(48),
      holdReason: null,
      status: "open",
      disputeId: null,
    },
    {
      id: "inv_hap_7742",
      invoiceNumber: "HLCU-DM-774211",
      chargeType: "demurrage",
      direction: "import",
      billingParty: "Hapag-Lloyd",
      billingPartyType: "VOCC",
      billedParty: BILLED,
      bolNumber: "HLCUHAM26044122",
      containerNumber: "HLXU7742115",
      port: "Houston",
      terminal: "Barbours Cut",
      liabilityBasis: "Consignee.",
      invoiceDate: ago(26),
      dueDate: day(4),
      freeTimeDays: 3,
      freeTimeStart: ago(39),
      freeTimeEnd: ago(36),
      availabilityDate: ago(39),
      earliestReturnDate: null,
      chargeDates: chargeSpan(33, 3),
      amountDue: 4440,
      tariffRule: null,
      dailyRate: 1480,
      contactEmail: "us.dnd@hlag.com",
      contactPhone: "+1 877 661 5456",
      disputeUrl: "https://www.hapag-lloyd.com/en/online-business/detention-demurrage.html",
      disputeWindowDays: 30,
      certFmcConsistent: true,
      certPerformanceClean: true,
      lastChargeDate: ago(33),
      holdReason: null,
      status: "open",
      disputeId: null,
    },
    {
      id: "inv_zim_9014",
      invoiceNumber: "ZIMU-DM-901447",
      chargeType: "demurrage",
      direction: "import",
      billingParty: "ZIM Integrated Shipping",
      billingPartyType: "VOCC",
      billedParty: BILLED,
      bolNumber: "ZIMUORF2466001",
      containerNumber: "ZCSU9014471",
      port: "Norfolk",
      terminal: "NIT Norfolk",
      liabilityBasis: "Named consignee on master bill.",
      invoiceDate: ago(28),
      dueDate: day(2),
      freeTimeDays: 4,
      freeTimeStart: ago(42),
      freeTimeEnd: ago(38),
      availabilityDate: ago(42),
      earliestReturnDate: null,
      chargeDates: null,
      amountDue: 7200,
      tariffRule: "ZIM US East Coast Demurrage 12",
      dailyRate: 1800,
      contactEmail: "usa.equipment@zim.com",
      contactPhone: "+1 866 744 7046",
      disputeUrl: "https://www.zim.com/tools/local-info",
      disputeWindowDays: 30,
      certFmcConsistent: true,
      certPerformanceClean: true,
      lastChargeDate: ago(34),
      holdReason: null,
      status: "open",
      disputeId: null,
    },
    {
      id: "inv_msc_4408",
      invoiceNumber: "MSC-DT-44081",
      chargeType: "detention",
      direction: "import",
      billingParty: "MSC Mediterranean Shipping",
      billingPartyType: "VOCC",
      billedParty: BILLED,
      bolNumber: "MEDUUN24040112",
      containerNumber: "MSCU4408123",
      port: "New York / New Jersey",
      terminal: "Maher Terminals",
      liabilityBasis: "Merchant responsible for equipment return under combined transport B/L.",
      invoiceDate: ago(21),
      dueDate: day(9),
      freeTimeDays: 5,
      freeTimeStart: ago(36),
      freeTimeEnd: ago(31),
      availabilityDate: ago(36),
      earliestReturnDate: ago(31),
      chargeDates: chargeSpan(26, 5),
      amountDue: 11050,
      tariffRule: "MSC Rule Tariff 004 — Detention",
      dailyRate: 2210,
      contactEmail: "dnd.us@msc.com",
      contactPhone: "+1 212 764 4800",
      disputeUrl: "https://www.msc.com/usa/help-centre/demurrage-detention",
      disputeWindowDays: 30,
      certFmcConsistent: true,
      certPerformanceClean: true,
      lastChargeDate: ago(26),
      holdReason:
        "Empty return refused 18–21 Aug: Maher reported no street-turn chassis. Hold is carrier/terminal, not merchant.",
      status: "open",
      disputeId: null,
    },
    {
      id: "inv_mae_2219",
      invoiceNumber: "MAEU-DM-221908",
      chargeType: "demurrage",
      direction: "import",
      billingParty: "Maersk A/S",
      billingPartyType: "VOCC",
      billedParty: BILLED,
      bolNumber: null,
      containerNumber: "MRKU2219087",
      port: "Savannah",
      terminal: "Garden City Terminal",
      liabilityBasis: "Consignee.",
      invoiceDate: ago(15),
      dueDate: day(15),
      freeTimeDays: 4,
      freeTimeStart: ago(29),
      freeTimeEnd: ago(25),
      availabilityDate: ago(29),
      earliestReturnDate: null,
      chargeDates: chargeSpan(22, 3),
      amountDue: 5600,
      tariffRule: "Maersk Demurrage Savannah 2.1",
      dailyRate: 1866,
      contactEmail: "us.detention@maersk.com",
      contactPhone: "+1 973 514 5000",
      disputeUrl: "https://www.maersk.com/support/demurrage-detention",
      disputeWindowDays: 30,
      certFmcConsistent: true,
      certPerformanceClean: true,
      lastChargeDate: ago(22),
      holdReason: null,
      status: "open",
      disputeId: null,
    },
    {
      id: "inv_cma_1904",
      invoiceNumber: "CMA-DM-190446",
      chargeType: "demurrage",
      direction: "import",
      billingParty: "CMA CGM",
      billingPartyType: "VOCC",
      billedParty: BILLED,
      bolNumber: "CMDUUSNYC247104",
      containerNumber: "CMAU1904466",
      port: "New York / New Jersey",
      terminal: "APM Terminals Elizabeth",
      liabilityBasis: "Consignee on bill of lading.",
      invoiceDate: ago(25),
      dueDate: day(5),
      freeTimeDays: 4,
      freeTimeStart: null,
      freeTimeEnd: ago(32),
      availabilityDate: ago(36),
      earliestReturnDate: null,
      chargeDates: chargeSpan(29, 4),
      amountDue: 18900,
      tariffRule: "CMA CGM Demurrage NY/NJ Rule 23",
      dailyRate: 4725,
      contactEmail: "us.dnd@cma-cgm.com",
      contactPhone: "+1 757 961 2100",
      disputeUrl: "https://www.cma-cgm.com/ebusiness/detention-demurrage",
      disputeWindowDays: 30,
      certFmcConsistent: false,
      certPerformanceClean: false,
      lastChargeDate: ago(29),
      holdReason: null,
      status: "open",
      disputeId: null,
    },
    {
      id: "inv_apm_0881",
      invoiceNumber: "APMT-DM-08817",
      chargeType: "demurrage",
      direction: "import",
      billingParty: "APM Terminals Elizabeth",
      billingPartyType: "MTO",
      billedParty: BILLED,
      bolNumber: "MEDUUN24031890",
      containerNumber: "TGHU0881722",
      port: null,
      terminal: "APM Terminals Elizabeth",
      liabilityBasis: "Terminal user under schedule 2024-11.",
      invoiceDate: ago(19),
      dueDate: day(11),
      freeTimeDays: 4,
      freeTimeStart: ago(31),
      freeTimeEnd: ago(27),
      availabilityDate: ago(31),
      earliestReturnDate: null,
      chargeDates: chargeSpan(24, 3),
      amountDue: 3850,
      tariffRule: "APMT Elizabeth Terminal Schedule 2024-11 §7",
      dailyRate: 1283,
      contactEmail: "billing.elizabeth@apmterminals.com",
      contactPhone: "+1 908 351 7777",
      disputeUrl: "https://www.apmterminals.com/en/elizabeth/practical-information",
      disputeWindowDays: 30,
      certFmcConsistent: true,
      certPerformanceClean: true,
      lastChargeDate: ago(24),
      holdReason: null,
      status: "open",
      disputeId: null,
    },
    {
      id: "inv_evr_6610",
      invoiceNumber: "EGLV-DM-661028",
      chargeType: "demurrage",
      direction: "import",
      billingParty: "Evergreen Line",
      billingPartyType: "VOCC",
      billedParty: BILLED,
      bolNumber: "EGLV0033608821",
      containerNumber: "EGHU6610284",
      port: "Los Angeles",
      terminal: "Everport LA",
      liabilityBasis: "Consignee.",
      invoiceDate: ago(10),
      dueDate: day(20),
      freeTimeDays: 4,
      freeTimeStart: ago(22),
      freeTimeEnd: ago(18),
      availabilityDate: ago(22),
      earliestReturnDate: null,
      chargeDates: chargeSpan(16, 2),
      amountDue: 2200,
      tariffRule: "Evergreen Demurrage POLA T-04",
      dailyRate: 1100,
      contactEmail: "usa.dnd@evergreen-shipping.us",
      contactPhone: "+1 201 761 3000",
      disputeUrl: "https://www.shipmentlink.com/tmd1/jsp/TMD1_DnD.jsp",
      disputeWindowDays: 30,
      certFmcConsistent: true,
      certPerformanceClean: true,
      lastChargeDate: ago(16),
      holdReason: null,
      status: "open",
      disputeId: null,
    },
    {
      id: "inv_one_7733",
      invoiceNumber: "ONEY-DM-773301",
      chargeType: "demurrage",
      direction: "import",
      billingParty: "Ocean Network Express",
      billingPartyType: "VOCC",
      billedParty: BILLED,
      bolNumber: "ONEYNYC2488001",
      containerNumber: "TCLU7733012",
      port: "New York / New Jersey",
      terminal: "Maher Terminals",
      liabilityBasis: "Consignee.",
      invoiceDate: ago(40),
      dueDate: ago(10),
      freeTimeDays: 4,
      freeTimeStart: ago(55),
      freeTimeEnd: ago(51),
      availabilityDate: ago(55),
      earliestReturnDate: null,
      chargeDates: chargeSpan(47, 5),
      amountDue: 14200,
      tariffRule: "ONE US Demurrage 3.1",
      dailyRate: 2840,
      contactEmail: "usa.dnd@one-line.com",
      contactPhone: "+1 201 678 4000",
      disputeUrl: "https://ecomm.one-line.com/one-ecom/dispute",
      disputeWindowDays: 30,
      certFmcConsistent: false,
      certPerformanceClean: false,
      lastChargeDate: ago(47),
      holdReason: null,
      status: "recovered",
      disputeId: "dsp_one_7733",
    },
    {
      id: "inv_cos_5581",
      invoiceNumber: "COSCO-DT-558190",
      chargeType: "detention",
      direction: "import",
      billingParty: "COSCO Shipping",
      billingPartyType: "VOCC",
      billedParty: BILLED,
      bolNumber: "COSU6369109901",
      containerNumber: "CSNU5581906",
      port: "Long Beach",
      terminal: "TTI Long Beach",
      liabilityBasis: "Merchant for equipment.",
      invoiceDate: ago(16),
      dueDate: day(14),
      freeTimeDays: 4,
      freeTimeStart: ago(30),
      freeTimeEnd: ago(26),
      availabilityDate: ago(30),
      earliestReturnDate: ago(26),
      chargeDates: chargeSpan(20, 4),
      amountDue: 8880,
      tariffRule: "COSCO America Detention POLB 1.2",
      dailyRate: 2220,
      contactEmail: "dnd.usa@coscon.com",
      contactPhone: "+1 866 830 2550",
      disputeUrl: "https://elines.coscoshipping.com/ebusiness/help/dnd",
      disputeWindowDays: 30,
      certFmcConsistent: true,
      certPerformanceClean: false,
      lastChargeDate: ago(20),
      holdReason: null,
      status: "disputed",
      disputeId: "dsp_cos_5581",
    },
    {
      id: "inv_hap_1022",
      invoiceNumber: "HLCU-DM-102244",
      chargeType: "demurrage",
      direction: "import",
      billingParty: "Hapag-Lloyd",
      billingPartyType: "VOCC",
      billedParty: BILLED,
      bolNumber: "HLCUHAM26050018",
      containerNumber: "HLXU1022449",
      port: "Houston",
      terminal: "Barbours Cut",
      liabilityBasis: "Consignee named on bill of lading.",
      invoiceDate: ago(6),
      dueDate: day(24),
      freeTimeDays: 3,
      freeTimeStart: ago(14),
      freeTimeEnd: ago(11),
      availabilityDate: ago(14),
      earliestReturnDate: null,
      chargeDates: chargeSpan(10, 1),
      amountDue: 1950,
      tariffRule: "Hapag-Lloyd Houston Demurrage 9.2",
      dailyRate: 1950,
      contactEmail: "us.dnd@hlag.com",
      contactPhone: "+1 877 661 5456",
      disputeUrl: "https://www.hapag-lloyd.com/en/online-business/detention-demurrage.html",
      disputeWindowDays: 30,
      certFmcConsistent: true,
      certPerformanceClean: true,
      lastChargeDate: ago(10),
      holdReason: null,
      status: "paid",
      disputeId: null,
    },
    {
      id: "inv_msc_0917",
      invoiceNumber: "MSC-DM-09174",
      chargeType: "demurrage",
      direction: "import",
      billingParty: "MSC Mediterranean Shipping",
      billingPartyType: "VOCC",
      billedParty: BILLED,
      bolNumber: "MEDUUN24051220",
      containerNumber: "MSCU0917488",
      port: "New York / New Jersey",
      terminal: "APM Terminals Elizabeth",
      liabilityBasis: "Consignee.",
      invoiceDate: ago(29),
      dueDate: null,
      freeTimeDays: 4,
      freeTimeStart: ago(44),
      freeTimeEnd: ago(40),
      availabilityDate: ago(44),
      earliestReturnDate: null,
      chargeDates: chargeSpan(36, 4),
      amountDue: 6100,
      tariffRule: "MSC Rule Tariff 004 — Demurrage NY/NJ",
      dailyRate: 1525,
      contactEmail: "dnd.us@msc.com",
      contactPhone: "+1 212 764 4800",
      disputeUrl: "https://www.msc.com/usa/help-centre/demurrage-detention",
      disputeWindowDays: 30,
      certFmcConsistent: true,
      certPerformanceClean: true,
      lastChargeDate: ago(36),
      holdReason: null,
      status: "open",
      disputeId: null,
    },
    {
      id: "inv_zim_2205",
      invoiceNumber: "ZIMU-DT-220511",
      chargeType: "detention",
      direction: "export",
      billingParty: "ZIM Integrated Shipping",
      billingPartyType: "VOCC",
      billedParty: BILLED,
      bolNumber: "ZIMUORF2477910",
      containerNumber: "ZCSU2205118",
      port: "Norfolk",
      terminal: "NIT Norfolk",
      liabilityBasis: "Shipper of record on export booking ZIM-EX-77910.",
      invoiceDate: ago(23),
      dueDate: day(7),
      freeTimeDays: 5,
      freeTimeStart: ago(37),
      freeTimeEnd: ago(32),
      availabilityDate: null,
      earliestReturnDate: null,
      chargeDates: chargeSpan(28, 4),
      amountDue: 10400,
      tariffRule: "ZIM US Export Detention 12",
      dailyRate: 2600,
      contactEmail: "usa.equipment@zim.com",
      contactPhone: "+1 866 744 7046",
      disputeUrl: "https://www.zim.com/tools/local-info",
      disputeWindowDays: 30,
      certFmcConsistent: true,
      certPerformanceClean: true,
      lastChargeDate: ago(28),
      holdReason: null,
      status: "open",
      disputeId: null,
    },
    {
      id: "inv_mae_8801",
      invoiceNumber: "MAEU-DM-880144",
      chargeType: "demurrage",
      direction: "import",
      billingParty: "Maersk A/S",
      billingPartyType: "VOCC",
      billedParty: BILLED,
      bolNumber: "MAEU588299001",
      containerNumber: "MRKU8801442",
      port: "New York / New Jersey",
      terminal: "APM Terminals Elizabeth",
      liabilityBasis: null,
      invoiceDate: ago(16),
      dueDate: day(14),
      freeTimeDays: 4,
      freeTimeStart: ago(28),
      freeTimeEnd: ago(24),
      availabilityDate: ago(28),
      earliestReturnDate: null,
      chargeDates: chargeSpan(21, 3),
      amountDue: 4780,
      tariffRule: "Maersk Demurrage NY/NJ 2.4",
      dailyRate: 1593,
      contactEmail: "us.detention@maersk.com",
      contactPhone: "+1 973 514 5000",
      disputeUrl: "https://www.maersk.com/support/demurrage-detention",
      disputeWindowDays: 30,
      certFmcConsistent: true,
      certPerformanceClean: true,
      lastChargeDate: ago(21),
      holdReason: null,
      status: "open",
      disputeId: null,
    },
    {
      id: "inv_cma_3007",
      invoiceNumber: "CMA-DM-300711",
      chargeType: "demurrage",
      direction: "import",
      billingParty: "CMA CGM",
      billingPartyType: "VOCC",
      billedParty: BILLED,
      bolNumber: "CMDUUSNYC2411009",
      containerNumber: "CMAU3007115",
      port: "New York / New Jersey",
      terminal: "Maher Terminals",
      liabilityBasis: "Consignee.",
      invoiceDate: ago(33),
      dueDate: ago(3),
      freeTimeDays: 4,
      freeTimeStart: ago(50),
      freeTimeEnd: ago(46),
      availabilityDate: ago(50),
      earliestReturnDate: null,
      chargeDates: chargeSpan(42, 4),
      amountDue: 9600,
      tariffRule: "CMA CGM Demurrage NY/NJ Rule 23",
      dailyRate: 2400,
      contactEmail: "us.dnd@cma-cgm.com",
      contactPhone: "+1 757 961 2100",
      disputeUrl: "https://www.cma-cgm.com/ebusiness/detention-demurrage",
      disputeWindowDays: 20,
      certFmcConsistent: false,
      certPerformanceClean: false,
      lastChargeDate: ago(42),
      holdReason: null,
      status: "open",
      disputeId: null,
    },
  ];

  const gates: GateEvent[] = [
    {
      id: "gte_1",
      containerNumber: "CMAU8471203",
      terminal: "WBCT",
      eventType: "discharge",
      timestamp: stamp(34, 6, 12),
      source: "terminal",
      notes: "Vessel CMA CGM Marco Polo, bay 42.",
    },
    {
      id: "gte_2",
      containerNumber: "CMAU8471203",
      terminal: "WBCT",
      eventType: "available",
      timestamp: stamp(32, 14, 40),
      source: "terminal",
      notes: "Yard available. Customs hold released 13:10.",
    },
    {
      id: "gte_3",
      containerNumber: "CMAU8471203",
      terminal: "WBCT",
      eventType: "available",
      timestamp: stamp(31, 9, 5),
      source: "tms",
      notes: "CargoWise availability ping — 18h 25m after terminal gate.",
    },
    {
      id: "gte_4",
      containerNumber: "CMAU8471203",
      terminal: "WBCT",
      eventType: "outgate",
      timestamp: stamp(29, 16, 2),
      source: "terminal",
      notes: "Dray: Northbridge fleet unit 441.",
    },
    {
      id: "gte_5",
      containerNumber: "MSCU4408123",
      terminal: "Maher Terminals",
      eventType: "outgate",
      timestamp: stamp(35, 11, 20),
      source: "terminal",
      notes: "Full outgate to Kearny CFS.",
    },
    {
      id: "gte_6",
      containerNumber: "MSCU4408123",
      terminal: "Maher Terminals",
      eventType: "hold",
      timestamp: stamp(30, 8, 0),
      source: "terminal",
      notes: "Empty return appointment rejected: no street-turn chassis. Pool 44 dry.",
    },
    {
      id: "gte_7",
      containerNumber: "MSCU4408123",
      terminal: "Maher Terminals",
      eventType: "hold",
      timestamp: stamp(28, 8, 0),
      source: "terminal",
      notes: "Second refused empty — chassis shortage continues.",
    },
    {
      id: "gte_8",
      containerNumber: "MSCU4408123",
      terminal: "Maher Terminals",
      eventType: "empty_return",
      timestamp: stamp(26, 15, 44),
      source: "terminal",
      notes: "Empty accepted after chassis allocation.",
    },
    {
      id: "gte_9",
      containerNumber: "EGHU6610284",
      terminal: "Everport LA",
      eventType: "discharge",
      timestamp: stamp(23, 4, 50),
      source: "terminal",
      notes: null,
    },
    {
      id: "gte_10",
      containerNumber: "EGHU6610284",
      terminal: "Everport LA",
      eventType: "available",
      timestamp: stamp(22, 7, 12),
      source: "terminal",
      notes: "Available on terminal inventory.",
    },
    {
      id: "gte_11",
      containerNumber: "EGHU6610284",
      terminal: "Everport LA",
      eventType: "available",
      timestamp: stamp(22, 11, 18),
      source: "tms",
      notes: "Tango TMS sync — 4h 6m lag. Dray window compressed past first shift.",
    },
    {
      id: "gte_12",
      containerNumber: "EGHU6610284",
      terminal: "Everport LA",
      eventType: "outgate",
      timestamp: stamp(20, 13, 41),
      source: "terminal",
      notes: null,
    },
    {
      id: "gte_13",
      containerNumber: "MSCU2948176",
      terminal: "APM Terminals Elizabeth",
      eventType: "discharge",
      timestamp: stamp(39, 5, 3),
      source: "terminal",
      notes: null,
    },
    {
      id: "gte_14",
      containerNumber: "MSCU2948176",
      terminal: "APM Terminals Elizabeth",
      eventType: "available",
      timestamp: stamp(37, 10, 22),
      source: "terminal",
      notes: "Available. Invoice omits this date.",
    },
    {
      id: "gte_15",
      containerNumber: "MSCU2948176",
      terminal: "APM Terminals Elizabeth",
      eventType: "outgate",
      timestamp: stamp(33, 9, 15),
      source: "terminal",
      notes: null,
    },
    {
      id: "gte_16",
      containerNumber: "CSNU1190448",
      terminal: "TTI Long Beach",
      eventType: "discharge",
      timestamp: stamp(21, 8, 0),
      source: "terminal",
      notes: null,
    },
    {
      id: "gte_17",
      containerNumber: "CSNU1190448",
      terminal: "TTI Long Beach",
      eventType: "available",
      timestamp: stamp(20, 6, 40),
      source: "terminal",
      notes: "Matches invoice availability.",
    },
    {
      id: "gte_18",
      containerNumber: "CSNU1190448",
      terminal: "TTI Long Beach",
      eventType: "available",
      timestamp: stamp(20, 7, 5),
      source: "tms",
      notes: "TMS caught up in 25 minutes.",
    },
    {
      id: "gte_19",
      containerNumber: "CSNU1190448",
      terminal: "TTI Long Beach",
      eventType: "outgate",
      timestamp: stamp(16, 14, 12),
      source: "terminal",
      notes: null,
    },
    {
      id: "gte_20",
      containerNumber: "TCLU5520189",
      terminal: "APM Terminals Elizabeth",
      eventType: "empty_return",
      timestamp: stamp(48, 16, 8),
      source: "terminal",
      notes: "Last charge day. Invoice issued 36 days later.",
    },
    {
      id: "gte_21",
      containerNumber: "HLXU1022449",
      terminal: "Barbours Cut",
      eventType: "available",
      timestamp: stamp(14, 9, 0),
      source: "terminal",
      notes: "Clean cycle.",
    },
    {
      id: "gte_22",
      containerNumber: "HLXU1022449",
      terminal: "Barbours Cut",
      eventType: "outgate",
      timestamp: stamp(10, 11, 33),
      source: "terminal",
      notes: null,
    },
  ];

  return { invoices, gates };
}

export const DESK = {
  org: "Northbridge Logistics LLC",
  scac: "NBLQ",
  desk: "Port of New York / New Jersey",
  manager: "Elena Vasquez",
  title: "Manager, Drayage Operations",
  address: "210 Harborside Drive, Newark, NJ 07114",
  email: "e.vasquez@northbridge-logistics.example",
  phone: "+1 973 555 0144",
};
