import type { ConnectorDef } from "./types.ts";

export const CONNECTORS: ConnectorDef[] = [
  {
    id: "cargowise",
    name: "CargoWise One",
    vendor: "WiseTech Global",
    kind: "tms",
    protocol: "eAdaptor UniversalShipment",
    format: "cargowise",
    blurb: "Forwarding consol, container dates, and job costing. TMS availability often lags the terminal tape by hours.",
    endpoint: "https://eadaptor.sandbox.cargowise.com/eAdaptor",
    accountLabel: "Enterprise ID",
    sandboxAccount: "NORTHBRIDGE",
    sandboxKey: "cw1_sandbox_northbridge",
  },
  {
    id: "tango",
    name: "Tango TMS",
    vendor: "Tango Transport",
    kind: "tms",
    protocol: "Load + milestone JSON",
    format: "tango",
    blurb: "Dray load export with accessorials and milestone pings. Use against a terminal feed to surface compressed windows.",
    endpoint: "https://api.sandbox.tangotms.com/v2",
    accountLabel: "Company code",
    sandboxAccount: "NBL-NYNJ",
    sandboxKey: "tango_sandbox_nbl",
  },
  {
    id: "msc",
    name: "MSC eCommerce",
    vendor: "Mediterranean Shipping",
    kind: "carrier",
    protocol: "Invoice JSON",
    format: "msc",
    blurb: "Demurrage and detention invoices as MSC posts them. Certifications and availability are frequently incomplete.",
    endpoint: "https://api.sandbox.msc.com/dnd/invoices",
    accountLabel: "SCAC / payer",
    sandboxAccount: "MSCU / NORTHBRIDGE",
    sandboxKey: "msc_sandbox_nbl",
  },
  {
    id: "maersk",
    name: "Maersk Developer",
    vendor: "Maersk A/S",
    kind: "carrier",
    protocol: "DCSA-style invoice JSON",
    format: "maersk",
    blurb: "Equipment invoices with stated availability. Cross-check against Maher or APM gate events.",
    endpoint: "https://api.sandbox.maersk.com/invoices",
    accountLabel: "Consumer key",
    sandboxAccount: "MAEU-NBL",
    sandboxKey: "maersk_sandbox_nbl",
  },
  {
    id: "cma",
    name: "CMA CGM EDI",
    vendor: "CMA CGM",
    kind: "carrier",
    protocol: "X12 310 Freight Invoice",
    format: "edi310",
    blurb: "Mailbox drop of 310s. Missing DTM free-time or N1 dispute contact voids the obligation under 541.6.",
    endpoint: "edi://sandbox.cma-cgm.com/x12/310",
    accountLabel: "ISA receiver / mailbox",
    sandboxAccount: "NORTHBRIDGE",
    sandboxKey: "cma_edi_sandbox",
  },
  {
    id: "apm",
    name: "APM Terminals",
    vendor: "APM Terminals Elizabeth",
    kind: "terminal",
    protocol: "TOS gate JSON",
    format: "tos",
    blurb: "Discharge, availability, and outgate from the Elizabeth TOS. Ground truth for carrier availability dates.",
    endpoint: "https://api.sandbox.apmterminals.com/gate",
    accountLabel: "Terminal code",
    sandboxAccount: "APMT-EWR",
    sandboxKey: "apm_tos_sandbox",
  },
  {
    id: "maher",
    name: "Maher Terminals",
    vendor: "Maher Terminals LLC",
    kind: "terminal",
    protocol: "EDIFACT CODECO",
    format: "codeco",
    blurb: "Gate-in / gate-out CODECO from the Port Newark complex. Pair with Maersk and MSC detention invoices.",
    endpoint: "edi://sandbox.maherterminals.com/codeco",
    accountLabel: "UNB recipient",
    sandboxAccount: "NORTHBRIDGE",
    sandboxKey: "maher_codeco_sandbox",
  },
  {
    id: "pnct",
    name: "PNCT",
    vendor: "Port Newark Container Terminal",
    kind: "terminal",
    protocol: "TOS gate JSON",
    format: "tos",
    blurb: "PNCT yard moves. Use when the invoice names Port Newark as the place of availability.",
    endpoint: "https://api.sandbox.pnct.net/moves",
    accountLabel: "Facility code",
    sandboxAccount: "PNCT-EWR",
    sandboxKey: "pnct_tos_sandbox",
  },
  {
    id: "noaa-nynj",
    name: "NOAA NY Harbor",
    vendor: "NOAA CO-OPS + NDBC",
    kind: "open",
    protocol: "CO-OPS / NDBC (no key)",
    format: "noaa",
    blurb: "Live tide at The Battery, Newark Bay current, Bayonne Bridge air gap, and entrance seas from buoy 44065. Port-condition evidence under 545.5 — not an invoice feed.",
    endpoint: "https://api.tidesandcurrents.noaa.gov/api/prod/datagetter",
    accountLabel: "Stations",
    sandboxAccount: "8518750 / n07010 / 8519461 / 44065",
    sandboxKey: "public",
  },
  {
    id: "nws-nynj",
    name: "NWS NY Harbor",
    vendor: "National Weather Service",
    kind: "open",
    protocol: "api.weather.gov (no key)",
    format: "nws",
    blurb: "Elizabeth forecast, New York Harbor coastal waters (ANZ338), and active NJ alerts. Thunderstorms, fog, and heat go to the 545.5 pack as pickup-impractical evidence.",
    endpoint: "https://api.weather.gov",
    accountLabel: "Office / zone",
    sandboxAccount: "OKX / ANZ338 / NJZ108",
    sandboxKey: "public",
  },
  {
    id: "pnct-public",
    name: "PNCT public board",
    vendor: "Port Newark Container Terminal",
    kind: "open",
    protocol: "Public vessel schedule HTML (no key)",
    format: "pnct",
    blurb: "Live PNCT vessel board and gate hours scraped from the public site. Real MSC and Atlantic sailings, cutoffs, and closed days — still not carrier D&D invoices.",
    endpoint: "https://www.pnct.net/VesselSchedule",
    accountLabel: "Board",
    sandboxAccount: "public",
    sandboxKey: "public",
  },
  {
    id: "osm-nynj",
    name: "OSM terminals",
    vendor: "OpenStreetMap Nominatim",
    kind: "open",
    protocol: "Nominatim JSON (no key)",
    format: "osm",
    blurb: "Live facility footprints for APM Elizabeth, Maher, and PNCT from OpenStreetMap. Confirms place-of-availability names on 541.6 invoices.",
    endpoint: "https://nominatim.openstreetmap.org/search",
    accountLabel: "Query",
    sandboxAccount: "APM / Maher / PNCT",
    sandboxKey: "public",
  },
  {
    id: "digitraffic",
    name: "Fintraffic Portnet",
    vendor: "Digitraffic / Fintraffic",
    kind: "open",
    protocol: "Port-call REST (no key)",
    format: "digitraffic",
    blurb: "Live cargo-ship port calls from the Finnish Portnet feed. Real vessels and timestamps. Baltic geography — proof the live pipe works, not a NY/NJ invoice book.",
    endpoint: "https://meri.digitraffic.fi/api/port-call/v1/port-calls",
    accountLabel: "Feed",
    sandboxAccount: "public",
    sandboxKey: "public",
  },
];

export function connectorById(id: string) {
  return CONNECTORS.find((c) => c.id === id) ?? null;
}

export const KIND_LABEL: Record<ConnectorDef["kind"], string> = {
  open: "Open data",
  tms: "TMS",
  carrier: "Carrier",
  terminal: "Terminal",
};

/** Default demo stack: TMS + carrier invoice + terminal tape (proves lag). */
export const NORTHBRIDGE_STACK = ["msc", "cargowise", "apm"] as const;
export const OPEN_STACK = ["noaa-nynj", "nws-nynj", "pnct-public", "osm-nynj"] as const;
