/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppApiDocsRouteImport } from './routes/_app/api-docs'
import { Route as AppConnectorsRouteImport } from './routes/_app/connectors'
import { Route as AppDisputesRouteImport } from './routes/_app/disputes'
import { Route as AppGatesRouteImport } from './routes/_app/gates'
import { Route as AppIngestRouteImport } from './routes/_app/ingest'
import { Route as AppInvoicesRouteImport } from './routes/_app/invoices'
import { Route as AppRulesRouteImport } from './routes/_app/rules'
import { Route as AppDisputesIndexRouteImport } from './routes/_app/disputes.index'
import { Route as AppDisputesDisputeIdRouteImport } from './routes/_app/disputes.$disputeId'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app/invoices.index'
import { Route as AppInvoicesInvoiceIdRouteImport } from './routes/_app/invoices.$invoiceId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1ConnectorsRouteImport } from './routes/api/v1/connectors'
import { Route as ApiV1IngestRouteImport } from './routes/api/v1/ingest'
import { Route as ApiV1RulesRouteImport } from './routes/api/v1/rules'
import { Route as ApiV1ScanRouteImport } from './routes/api/v1/scan'
import { Route as ApiV1SourcesSourceIdRouteImport } from './routes/api/v1/sources.$sourceId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppApiDocsRoute = AppApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectorsRoute = AppConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => AppRoute,
} as any)
const AppDisputesRoute = AppDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AppRoute,
} as any)
const AppGatesRoute = AppGatesRouteImport.update({
  id: '/gates',
  path: '/gates',
  getParentRoute: () => AppRoute,
} as any)
const AppIngestRoute = AppIngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppDisputesIndexRoute = AppDisputesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDisputesRoute,
} as any)
const AppDisputesDisputeIdRoute = AppDisputesDisputeIdRouteImport.update({
  id: '/$disputeId',
  path: '/$disputeId',
  getParentRoute: () => AppDisputesRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInvoicesRoute,
} as any)
const AppInvoicesInvoiceIdRoute = AppInvoicesInvoiceIdRouteImport.update({
  id: '/$invoiceId',
  path: '/$invoiceId',
  getParentRoute: () => AppInvoicesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ConnectorsRoute = ApiV1ConnectorsRouteImport.update({
  id: '/api/v1/connectors',
  path: '/api/v1/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1IngestRoute = ApiV1IngestRouteImport.update({
  id: '/api/v1/ingest',
  path: '/api/v1/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RulesRoute = ApiV1RulesRouteImport.update({
  id: '/api/v1/rules',
  path: '/api/v1/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ScanRoute = ApiV1ScanRouteImport.update({
  id: '/api/v1/scan',
  path: '/api/v1/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SourcesSourceIdRoute = ApiV1SourcesSourceIdRouteImport.update({
  id: '/api/v1/sources/$sourceId',
  path: '/api/v1/sources/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/api-docs': typeof AppApiDocsRoute
  '/connectors': typeof AppConnectorsRoute
  '/disputes': typeof AppDisputesRouteWithChildren
  '/gates': typeof AppGatesRoute
  '/ingest': typeof AppIngestRoute
  '/invoices': typeof AppInvoicesRouteWithChildren
  '/rules': typeof AppRulesRoute
  '/disputes/$disputeId': typeof AppDisputesDisputeIdRoute
  '/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/connectors': typeof ApiV1ConnectorsRoute
  '/api/v1/ingest': typeof ApiV1IngestRoute
  '/api/v1/rules': typeof ApiV1RulesRoute
  '/api/v1/scan': typeof ApiV1ScanRoute
  '/disputes/': typeof AppDisputesIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/api/v1/sources/$sourceId': typeof ApiV1SourcesSourceIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/api-docs': typeof AppApiDocsRoute
  '/connectors': typeof AppConnectorsRoute
  '/gates': typeof AppGatesRoute
  '/ingest': typeof AppIngestRoute
  '/rules': typeof AppRulesRoute
  '/': typeof AppIndexRoute
  '/disputes/$disputeId': typeof AppDisputesDisputeIdRoute
  '/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/connectors': typeof ApiV1ConnectorsRoute
  '/api/v1/ingest': typeof ApiV1IngestRoute
  '/api/v1/rules': typeof ApiV1RulesRoute
  '/api/v1/scan': typeof ApiV1ScanRoute
  '/disputes': typeof AppDisputesIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/api/v1/sources/$sourceId': typeof ApiV1SourcesSourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/api-docs': typeof AppApiDocsRoute
  '/_app/connectors': typeof AppConnectorsRoute
  '/_app/disputes': typeof AppDisputesRouteWithChildren
  '/_app/gates': typeof AppGatesRoute
  '/_app/ingest': typeof AppIngestRoute
  '/_app/invoices': typeof AppInvoicesRouteWithChildren
  '/_app/rules': typeof AppRulesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/disputes/$disputeId': typeof AppDisputesDisputeIdRoute
  '/_app/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/connectors': typeof ApiV1ConnectorsRoute
  '/api/v1/ingest': typeof ApiV1IngestRoute
  '/api/v1/rules': typeof ApiV1RulesRoute
  '/api/v1/scan': typeof ApiV1ScanRoute
  '/_app/disputes/': typeof AppDisputesIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/api/v1/sources/$sourceId': typeof ApiV1SourcesSourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api-docs'
    | '/connectors'
    | '/disputes'
    | '/gates'
    | '/ingest'
    | '/invoices'
    | '/rules'
    | '/disputes/$disputeId'
    | '/invoices/$invoiceId'
    | '/api/auth/$'
    | '/api/v1/connectors'
    | '/api/v1/ingest'
    | '/api/v1/rules'
    | '/api/v1/scan'
    | '/disputes/'
    | '/invoices/'
    | '/api/v1/sources/$sourceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/api-docs'
    | '/connectors'
    | '/gates'
    | '/ingest'
    | '/rules'
    | '/'
    | '/disputes/$disputeId'
    | '/invoices/$invoiceId'
    | '/api/auth/$'
    | '/api/v1/connectors'
    | '/api/v1/ingest'
    | '/api/v1/rules'
    | '/api/v1/scan'
    | '/disputes'
    | '/invoices'
    | '/api/v1/sources/$sourceId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/api-docs'
    | '/_app/connectors'
    | '/_app/disputes'
    | '/_app/gates'
    | '/_app/ingest'
    | '/_app/invoices'
    | '/_app/rules'
    | '/_app/'
    | '/_app/disputes/$disputeId'
    | '/_app/invoices/$invoiceId'
    | '/api/auth/$'
    | '/api/v1/connectors'
    | '/api/v1/ingest'
    | '/api/v1/rules'
    | '/api/v1/scan'
    | '/_app/disputes/'
    | '/_app/invoices/'
    | '/api/v1/sources/$sourceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1ConnectorsRoute: typeof ApiV1ConnectorsRoute
  ApiV1IngestRoute: typeof ApiV1IngestRoute
  ApiV1RulesRoute: typeof ApiV1RulesRoute
  ApiV1ScanRoute: typeof ApiV1ScanRoute
  ApiV1SourcesSourceIdRoute: typeof ApiV1SourcesSourceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api-docs': {
      id: '/_app/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof AppApiDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connectors': {
      id: '/_app/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof AppConnectorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/disputes': {
      id: '/_app/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof AppDisputesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gates': {
      id: '/_app/gates'
      path: '/gates'
      fullPath: '/gates'
      preLoaderRoute: typeof AppGatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ingest': {
      id: '/_app/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof AppIngestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rules': {
      id: '/_app/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/disputes/': {
      id: '/_app/disputes/'
      path: '/'
      fullPath: '/disputes/'
      preLoaderRoute: typeof AppDisputesIndexRouteImport
      parentRoute: typeof AppDisputesRoute
    }
    '/_app/disputes/$disputeId': {
      id: '/_app/disputes/$disputeId'
      path: '/$disputeId'
      fullPath: '/disputes/$disputeId'
      preLoaderRoute: typeof AppDisputesDisputeIdRouteImport
      parentRoute: typeof AppDisputesRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    '/_app/invoices/$invoiceId': {
      id: '/_app/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AppInvoicesInvoiceIdRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/connectors': {
      id: '/api/v1/connectors'
      path: '/api/v1/connectors'
      fullPath: '/api/v1/connectors'
      preLoaderRoute: typeof ApiV1ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/ingest': {
      id: '/api/v1/ingest'
      path: '/api/v1/ingest'
      fullPath: '/api/v1/ingest'
      preLoaderRoute: typeof ApiV1IngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/rules': {
      id: '/api/v1/rules'
      path: '/api/v1/rules'
      fullPath: '/api/v1/rules'
      preLoaderRoute: typeof ApiV1RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/scan': {
      id: '/api/v1/scan'
      path: '/api/v1/scan'
      fullPath: '/api/v1/scan'
      preLoaderRoute: typeof ApiV1ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/sources/$sourceId': {
      id: '/api/v1/sources/$sourceId'
      path: '/api/v1/sources/$sourceId'
      fullPath: '/api/v1/sources/$sourceId'
      preLoaderRoute: typeof ApiV1SourcesSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppDisputesRouteChildren {
  AppDisputesDisputeIdRoute: typeof AppDisputesDisputeIdRoute
  AppDisputesIndexRoute: typeof AppDisputesIndexRoute
}

const AppDisputesRouteChildren: AppDisputesRouteChildren = {
  AppDisputesDisputeIdRoute: AppDisputesDisputeIdRoute,
  AppDisputesIndexRoute: AppDisputesIndexRoute,
}

const AppDisputesRouteWithChildren = AppDisputesRoute._addFileChildren(
  AppDisputesRouteChildren,
)

interface AppInvoicesRouteChildren {
  AppInvoicesInvoiceIdRoute: typeof AppInvoicesInvoiceIdRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
}

const AppInvoicesRouteChildren: AppInvoicesRouteChildren = {
  AppInvoicesInvoiceIdRoute: AppInvoicesInvoiceIdRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
}

const AppInvoicesRouteWithChildren = AppInvoicesRoute._addFileChildren(
  AppInvoicesRouteChildren,
)

interface AppRouteChildren {
  AppApiDocsRoute: typeof AppApiDocsRoute
  AppConnectorsRoute: typeof AppConnectorsRoute
  AppDisputesRoute: typeof AppDisputesRouteWithChildren
  AppGatesRoute: typeof AppGatesRoute
  AppIngestRoute: typeof AppIngestRoute
  AppInvoicesRoute: typeof AppInvoicesRouteWithChildren
  AppRulesRoute: typeof AppRulesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApiDocsRoute: AppApiDocsRoute,
  AppConnectorsRoute: AppConnectorsRoute,
  AppDisputesRoute: AppDisputesRouteWithChildren,
  AppGatesRoute: AppGatesRoute,
  AppIngestRoute: AppIngestRoute,
  AppInvoicesRoute: AppInvoicesRouteWithChildren,
  AppRulesRoute: AppRulesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1ConnectorsRoute: ApiV1ConnectorsRoute,
  ApiV1IngestRoute: ApiV1IngestRoute,
  ApiV1RulesRoute: ApiV1RulesRoute,
  ApiV1ScanRoute: ApiV1ScanRoute,
  ApiV1SourcesSourceIdRoute: ApiV1SourcesSourceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
